### ISSUE TITLE
LICENSE not included in pypi source

### ISSUE THREAD

**Issue by decathorpe** [toastdriven/pylev#11]
I'm working on packaging this project for fedora, and during the review, it was pointed out that the 1.2.0 sources that are available from PyPI don't include the LICENSE file - which they apparently should.

**Comment by eli-schwartz** [comment]
They don't include the testsuite either -- I recommend packaging from the github tarball in that case, which is what I plan to do for Arch Linux. Slightly complicating this is #10, so if need be I will probably end up using a commit archive instead of a tag.

It would be nice to have pylev released in such a way that either or both of Github and PyPI have all the pieces needed, rather than some in one place and some in another.

**Comment by toastdriven** [comment]
Apologies. This got lost in the shuffle during some major life events.

These will be addressed in another release in the (very) near future. Apologies for the difficulties.

**Comment by toastdriven** [comment]
Again, very sorry. The `v1.3.0` tarball on GH now has everything, including the `LICENSE`.

Additionally, there will shortly be a `v1.4.0`, which reflects the current state of `main`.

The last thing I'd mention here is that including the test suite with the PyPI package is generally not recommended. Packages off PyPI are meant to be consumption, not for additional development. So if you need the tests, the release tarball will always be the better choice.

**Comment by eli-schwartz** [comment]
> Apologies. This got lost in the shuffle during some major life events.

No worries. It's important to deal with actual priorities first.

> The last thing I'd mention here is that including the test suite with the PyPI package is generally not recommended. Packages off PyPI are meant to be consumption, not for additional development. So if you need the tests, the release tarball will always be the better choice.

The testsuite is not for "additional development", and PyPI tarballs *are* the release tarball -- it's a direct python equivalent to `autoreconf -fi && ./configure && make dist` (which does tar up testsuites). Both will prune a git repo of development-only data such as CI configuration, and generate other data not available in git (prebuilt manpages, configure scripts to go with configure.ac, Makefile.in to go with Makefile.am, in the python ecosystem there is cythonized *.c sources and poetry or flit generated setup.py).But traditionally testsuites are considered release data and in some cases e.g. tests provided in git submodules those will be in the release tarball but not in git and not in github-generated archives.

Github-generated archives are not always release tarball-worthy! If the project has generated files (autotools projects always do) then end users need to install development tools and run them before using the release build system. This is not *usually* the case with python. But again, see poetry/flit/cython. Anyway, github-generated archives are very often sufficient.

Testsuites are meant for end-user consumption in every computing field of endeavor other than python; the general ecosystem of python programmers is erroneously resistant to the idea that they're meant for end-user consumption in python too. :)

(End users acquiring software source code have a vested interest in checking that it performs as expected in their environment, e.g. with different dependencies or on different operating systems than it was originally tested in development on. And this software project may not have any external python module dependencies, but it does depend on the python runtime, and if it misbehaves on a major python upgrade then end users running unittests as part of their installation will catch that problem early.

I admit it would be nice if PyPA tooling supported opt-in running of testsuites during e.g. pip install, rather than that requiring custom build tooling. Conda does support this, so do linux distributions...)

So:

- PyPI sdists are meant to be complete source code (including testsuites).
- PyPI wheels are intended to just be the built artifacts for rapid installation (they can be directly unpacked by wheel installers, do not need to run setuptools first).

...

Anyway, thanks for git tagging the source. :) Using this is not a problem for me. I'm merely commenting as a general commentary on the state of the ecosystem since there's a lot of "common knowledge" out there that is misled and I believe the best way to solve this is to correct it whenever I have the opportunity to.

**Comment by toastdriven** [comment]
> Testsuites are meant for end-user consumption in every computing field of endeavor other than python; the general ecosystem of python programmers is erroneously resistant to the idea that they're meant for end-user consumption in python too. :)

Interesting. My view on releases is that I shouldn't be publishing the code if the code isn't 100% passing. And many times, the setup for the test suite isn't something I'd expect the end-user to do (setup an empty database, install & run a local empty Solr/Elasticsearch server, install & run a Redis instance, etc. - these are all examples from other packages I publish). It's not the case here, regardless.

Not looking to argue or flame. I think what you've said is very reasonable & I'll be thinking more in the future about including tests. And agreed on the ecosystem. When PyPA tooling adds running unit tests as part of the install, it'll definitely be time for me to make the change.
